name: Build Docker Image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t my-node-app02:0.001 .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Tag Docker image
        run: |
          docker images
          docker tag my-node-app02:0.001 ${{ secrets.DOCKER_USERNAME }}/my-node-app02:0.002

      - name: Push Docker image to Docker Hub
        run: |
          docker images
          docker push ${{ secrets.DOCKER_USERNAME }}/my-node-app02:0.002

      - name: Pull Docker image from Docker Hub
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/my-node-app02:0.002

      - name: Run Docker container
        run: |
          docker run -d -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/my-node-app02:0.002
          docker ps
